GFF/urls.py
from django.conf.urls import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^SendData/',include('SendData.urls')),
    url(r'^upload/',include('polls.urls', namespace = 'upload')),
    url(r'^show/',include('show.urls', namespace = 'show')),
]
"""

from . import view

urlpatterns = [
	url(r'^$', view.hello, name = 'home'),
	
	#url(r'^admin/', admin.site.urls),
]
"""

show/urls.py
from django.conf.urls import *
import show.views

urlpatterns = [

    url(r'^$', show.views.upload, name = 'show'),
    #url(r'upload/', show.views.upload, name = 'upload'),
    url(r'upload_file/(.+)/', show.views.upload_file, name = 'upload_file'),
    url(r'download_file/(.+)/', show.views.download_file, name = 'download_file'),
    url(r'modify_file/(?P<id>[^ ]*) (?P<fn>[^ ]*) (?P<cont>.*)/', show.views.modify_file, name = 'modify_file'),

    url(r'file_detail/(.+)/', show.views.file_detail, name = 'file_detail'),

    url(r'service_list/', show.views.service_list, name = 'service_list'),
    url(r'service_today/', show.views.service_today, name = 'service_today'),
    url(r'service_today_page/', show.views.service_today_page, name = 'service_today_page'),
    #url(r'^admin/', admin.site.urls),
]

show/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
# Create your models here.

class Service(models.Model):
	name = models.CharField(max_length = 30)
	upload_date = models.DateTimeField('date upload')
	def __str__(self):
		return self.name

class File(models.Model):
	service = models.ForeignKey(Service, on_delete = models.CASCADE)
	#filename = models.CharField(max_length = 30)
	content = models.CharField(max_length = 200)
	upload_File = models.FileField(upload_to = './upload')
	upload_date = models.DateTimeField('date uploaded')
	def __str__(self):
		return self.content

show/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django import forms
from django.forms import ModelForm
from django.http import HttpResponse, StreamingHttpResponse, HttpResponseRedirect
from show.models import *
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse	

# Create your views here.
class FileForm(forms.Form):
	service_name = forms.CharField(label = '服务')
	content = forms.CharField(label = '文件描述')
	upload_File = forms.FileField(label = '上传文件')

class ConfigForm(ModelForm):
	content = forms.CharField(label = '文件描述')
	upload_File = forms.FileField(label = '上传文件', required = False)
	class Meta:
		model = File
		fields = ('content', 'upload_File')

def upload(request):
	if request.method == "POST":
		ff = FileForm(request.POST, request.FILES)
		if ff.is_valid():
			name = ff.cleaned_data['service_name']
			content = ff.cleaned_data['content']
			upload_File = ff.cleaned_data['upload_File']

			s = Service.objects.filter(name = name) #get和filter有区别
			if s.count() == 0:
				s = Service()
				s.name = name
				s.upload_date =timezone.now()
				s.save()	
			else:
				s = Service.objects.get(name = name)
				s.upload_date =timezone.now()
				s.save()
			f = File()
			f.service = s
			f.content = content
			f.upload_File = upload_File
			f.upload_date = timezone.now()
			f.save()
			services = Service.objects.order_by('name')
			return render_to_response('service_list.html',{'services':services})
	else:
		ff = FileForm()
	return render(request, 'upload.html', {'ff':ff})

#上传配置文件
def upload_file(request, fn):
	if request.method == "POST":
		ff = ConfigForm(request.POST, request.FILES)
		if ff.is_valid():
			#name = ff.cleaned_data['service_name']
			content = ff.cleaned_data['content']
			upload_File = ff.cleaned_data['upload_File']
			s = Service.objects.get(name = fn)
			s.upload_date =timezone.now()
			s.save()
			f = File()
			f.service = s
			f.content = content
			f.upload_File = upload_File
			f.upload_date = timezone.now()
			f.save()
			services = Service.objects.get(name = fn)
			files = services.file_set.order_by('-upload_date')
			return HttpResponseRedirect(reverse('show:file_detail', args = [fn]))
	else:
		ff = ConfigForm()
	return render(request, 'upload.html', locals())


#修改配置文件：读取原文件有bug
def modify_file(request, id, fn, cont):
	if request.method == "POST":
		ff = ConfigForm(request.POST, request.FILES)
		if ff.is_valid():
			#name = ff.cleaned_data['service_name']
			content = ff.cleaned_data['content']
			upload_File = ff.cleaned_data['upload_File']
			s = Service.objects.get(name = fn)
			s.upload_date =timezone.now()
			s.save()
			f = s.file_set.get(id = id)
			f.content = content
			if upload_File:
				f.upload_File = upload_File
			f.upload_date = timezone.now()
			f.save()
			services = Service.objects.get(name = fn)
			files = services.file_set.order_by('-upload_date')

			#return render_to_response('file_detail.html',locals())
			return HttpResponseRedirect(reverse('show:file_detail', args = [fn]))
	else:
		s = Service.objects.get(name = fn)
		f = s.file_set.get(id = id)
		ff = ConfigForm(instance = f)
	return render(request, 'upload.html', locals())

#服务列表(分页)
def service_list(request):
	services = Service.objects.all()   #distinct表示重复出现只选取一次
	current_page = request.GET.get('p')
	keyword = request.GET.get("search","")
	if keyword:
		services = services.filter(name__contains = keyword)
	#每页显示10条记录
	paginator = Paginator(services, 1)
	try:
		posts = paginator.page(current_page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except:
		posts = paginator.page(paginator.num_pages)
	return render(request, 'service_list.html', locals())

#服务的配置列表
def file_detail(request,fn):
	s = Service.objects.get(name = fn)
	files = s.file_set.order_by('-upload_date')
	current_page = request.GET.get('p')
	keyword = request.GET.get("search","")
	if keyword:
		files = files.filter(content__contains = keyword)
	#每页显示10条记录
	paginator = Paginator(files, 5)
	try:
		posts = paginator.page(current_page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except:
		posts = paginator.page(paginator.num_pages)

	return render(request, 'file_detail.html', locals())

#下载文件
def download_file(request, fn):
	#从第七个字母读取文件名
	the_file_name = fn[7:]
	filename = fn
	response = StreamingHttpResponse(readFile(filename))
	response['Content-Type'] = 'application/octet-stream'
	response['Content-Disposition'] = 'attachment;filename="{0}"'.format(the_file_name);
	return response

def readFile(filename, chunk_size = 512):
	with open(filename, 'rb') as f:
		while True:
			c = f.read(chunk_size)
			if c:
				yield c
			else:
				break

#from django.views.decorators.csrf import csrf_protect
#@csrf_protect
def service_today(request):
	current_page = request.GET.get('p')
	services = Service.objects.filter(upload_date__startswith = timezone.now().date())
	keyword = request.GET.get("search","")
	if keyword:
		services = services.filter(name__contains = keyword)
	#每页显示1条记录
	paginator = Paginator(services, 1)
	try:
		posts = paginator.page(current_page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except:
		posts = paginator.page(paginator.num_pages)

	return render(request, 'service_today.html', locals())

def service_oneday(request, y, m, d):
	services = Service.objects.filter(upload_date__year = y, upload_date_month = m, upload_date_day = d)
	return render_to_response('service_today.html', locals())

#分页显示今天更新的服务列表
def service_today_page(request):
	current_page = request.GET.get('p')
	services = Service.objects.filter(upload_date__startswith = timezone.now().date())
	#每页显示1条记录
	paginator = Paginator(services, 1)
	try:
		posts = paginator.page(current_page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except:
		posts = paginator.page(paginator.num_pages)

	return render_to_response('service_today_page.html', locals())
"""
def search_service(request):
	servies = Service.objects.all()
	keyword = request.POST['search_words']
	#services = Service.objects.filter(name__contains = keyword | upload_date__contains = keyword)  #contain关键字
	
	return HttpResponse("search services")

def file_search(request, fn):
	keyword = request.POST['search_words']
	s = Service.objects.get(name = fn)
	files = s.file_set.filter(content__contains = keyword | upload_date__contains = keyword)
	return HttpResponse("search files")
"""

show/templates/file_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>File Detail</title>
	<style type="text/css">
	.text{text-align: center}
	.bottom{border-bottom-style: dashed; border-bottom-width: 1px}
	th{background-color:#c3dde0; width:200px;}
	td{width:200px;}
	.right{float:right;}
	.left{float: left;}
	h4{color: red}
	</style>
</head>
<body>
	<div>
		<div class = "right">
		<form method = "get" style="text-align: right;">
			{% csrf_token %} 
			<input type = "text" name = "search" />
			<input type = "submit" value = "搜索">
		</form>
		</div>
		<div>
		<h3 style="text-align: left; color:taupe;"><a href = "{% url 'show:service_list' %}">返回服务列表</a></h3>
		</div>

	<!--
		<div>
			<select>
				<option value = "name">内容</option>
				<option value = "date">日期</option>
			</select>
		</div>
	-->
	</div>

	<center>
	<h2 class = "text">{{fn}}的配置列表</h2>
	{% if keyword %}
		<h4 >搜索：{{keyword}}</h4>
	{% endif %}
	<table border="1"  cellspacing="0" cellpadding="0">
		<tr class = "text">
			<th>配置文件</th>
			<th>上传时间</th>
			<th>配置更新描述</th>
			<th>修改配置</th>
		</tr>
		{% for file in posts.object_list %}
		<tr>
			<td><a href = "{% url 'show:download_file' file.upload_File %}">{{file.upload_File}}</a></td>
			<td>{{file.upload_date|date:"Y-m-d H:i:s"}}</td>
			<td>{{file.content}}</td>
			<td class = "text"><a href = "{% url 'show:modify_file' id=file.id fn=fn cont=file.content %}">修改</a></td>
		</tr>
		{% endfor%}
	</table>
	<br>
	{% if posts.has_previous %}
		<a href = "?p={{ posts.previous_page_number }}&search={{ keyword }}">上一页</a>
	{% endif %}
	<span>
		{{ posts.number }} / {{ posts.paginator.num_pages }}
	</span>
	{% if posts.has_next %}
		<a href = "?p={{ posts.next_page_number }}&search={{ keyword }}">下一页</a>
	{% endif %}
	</center>
</body>
</html>

show/templates/service_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>Service List</title>
	<style type="text/css">
	.text{text-align: center}
	.bottom{border-bottom-style: dashed; border-bottom-width: 1px}
	th{background-color:#c3dde0; width:180px;}
	td{width:180px;}
	.right{float:right;}
	.left{float: left}
	h4{color: red}
	</style>
</head>
<body>
	<div>
		<div class = "right">
		<form method = "get" style="text-align: right;">
			{% csrf_token %} 
			<input type = "text" name = "search" />
			<input type = "submit" value = "搜索">
		</form>
		</div>
		<div>
		<h3 style="text-align: left; color:taupe;"><a href = "{% url 'show:service_list' %}">返回服务列表</a></h3>
		
		</div>

	<!--
		<div>
			<select>
				<option value = "name">内容</option>
				<option value = "date">日期</option>
			</select>
		</div>
	-->
	</div>
	<center>
	<h2>服务列表</h2>
	{% if keyword %}
		<h4 >搜索：{{keyword}}</h4>
	{% endif %}
	<table cellspacing="0" cellpadding="0">
		<tr class = "text">
			<th>服务名称</th>
			<th>更新时间</th>
			<th>上传配置文件</th>
		</tr>
		{% for service in posts.object_list %}
		<tr class = "text">
			<td><a href = "{% url 'show:file_detail' service.name %}">{{service.name}}</a></td>
			<td>{{service.upload_date|date:"Y-m-d H:i:s"}}</td>
			<td><a href = "{% url 'show:upload_file' service.name %}">上传配置</a></td>
		</tr>
		{% endfor%}
	</table>
	<br>
	{% if posts.has_previous %}
		<a href = "?p={{ posts.previouspage_number }}&search={{ keyword }}">上一页</a>
	{% endif %}
	<span>
		{{ posts.number }} / {{ posts.paginator.num_pages }}
	</span>
	{% if posts.has_next %}
		<a href = "?p={{ posts.next_page_number }}&search={{ keyword }}">下一页</a>
	{% endif %}
	<br><br>
	<span>
		<a href = "{% url 'show:service_today' %}">查看今天服务更新</a>
	</span>
	</center>
</body>
</html>

show/templates/service_today.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>Service List</title>
	<style type="text/css">
	.text{text-align: center}
	.bottom{border-bottom-style: dashed; border-bottom-width: 1px}
	th{background-color:#c3dde0; width:180px;}
	td{width:180px;}
	.right{float:right;}
	.center{float:center;}
	h4{color:red;}
	</style>
</head>
<body>
	<div>
		<div class = "right">
		<form method = "get" style="text-align: right;">
			{% csrf_token %} 
			<input type = "text" name = "search" />
			<input type = "submit" value = "搜索">
		</form>
		</div>

		<div>
		<h3 style="text-align: left; color:taupe;"><a href = "{% url 'show:service_list' %}">返回服务列表</a></h3>
		</div>

	<!--
		<div>
			<select>
				<option value = "name">内容</option>
				<option value = "date">日期</option>
			</select>
		</div>
	-->
	</div>
	<center>
	<h2>今天服务更新列表</h2>
	{% if keyword %}
		<h4 >搜索：{{keyword}}</h4>
	{% endif %}
	<table cellspacing="0" cellpadding="0">
		<tr class = "text">
			<th>服务名称</th>
			<th>更新时间</th>
			<th>上传配置文件</th>
		</tr>
		{% for service in posts.object_list %}
		<tr class = "text">
			<td><a href = "{% url 'show:file_detail' service.name %}">{{service.name}}</a></td>
			<td>{{service.upload_date|date:"Y-m-d H:i:s"}}</td>
			<td><a href = "{% url 'show:upload_file' service.name %}">上传配置</a></td>
		</tr>
		{% endfor%}
	</table>
	<br>
	{% if posts.has_previous %}
		<a href = "?p={{ posts.previous_page_number }}&search={{ keyword }}">上一页</a>
	{% endif %}
	<span>
		{{ posts.number }} / {{ posts.paginator.num_pages }}
	</span>
	{% if posts.has_next %}
		<a href = "?p={{ posts.next_page_number }}&search={{ keyword }}">下一页</a>
	{% endif %}	
	</center>
</body>
</html>

show/templates/service_today_page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>Service List</title>
	<style type="text/css">
	.text{text-align: center}
	.bottom{border-bottom-style: dashed; border-bottom-width: 1px}
	th{background-color:#c3dde0; width:180px;}
	td{width:180px;}
	</style>
</head>
<body>
	<h3 style="text-align: right; color:taupe;"><a href = "{% url 'show:service_list' %}">返回服务列表</a></h3>
	<center>
	<h2>今天服务更新列表</h2>
	<table cellspacing="0" cellpadding="0">
		<tr class = "text">
			<th>服务名称</th>
			<th>更新时间</th>
			<th>上传配置文件</th>
		</tr>
		{% for service in posts.object_list %}
		<tr class = "text">
			<td><a href = "{% url 'show:file_detail' service.name %}">{{service.name}}</a></td>
			<td>{{service.upload_date|date:"Y-m-d H:i:s"}}</td>
			<td><a href = "{% url 'show:upload_file' service.name %}">上传配置</a></td>
		</tr>
		{% endfor%}
	</table>
	<br>
	{% if posts.has_previous %}
		<a href = "?p={{ posts.previous_page_number }}">上一页</a>
	{% endif %}
	<span>
		{{ posts.number }} / {{ posts.paginator.num_pages }}
	</span>
	{% if posts.has_next %}
		<a href = "?p={{ posts.next_page_number }}">下一页</a>
	{% endif %}
	

	</center>
</body>
</html>

show/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>上传数据</title>
	<style type="text/css">
	input[type="checkbox"] {
    display: none;	
	}
	label[for="upload_File-clear_id"]{
		display: none;
	}
	label{
		display: block; 
		padding: 4px 10px 0 0;
    	float: left;
    	width: 100px;
	}
	.text{text-align: center}
	.div{margin:0 auto; width: 450px;}
	</style>
</head>
<body>
	<div>
	<h3 style="text-align: left; color:taupe;"><a href = "{% url 'show:service_list' %}">返回服务列表</a></h3>
	</div>
	<h2 class = "text">{{fn}}服务的配置文件上传</h2>
	<div class = "div">
	<form method = "post" enctype = "multipart/form-data">
		{% csrf_token %}
		{{ff.as_p}}
		<center>
		<input type = "submit" value = "上传">
		<input type = "reset" value = "重置">
		<center>
	</form>
	<div>
</body>
</html>