GFF/urls.py
from django.conf.urls import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^SendData/',include('SendData.urls')),
    url(r'^upload/',include('polls.urls', namespace = 'upload')),
    url(r'^show/',include('show.urls', namespace = 'show')),
]
"""

from . import view

urlpatterns = [
	url(r'^$', view.hello, name = 'home'),
	
	#url(r'^admin/', admin.site.urls),
]
"""

polls/urls.py
from django.conf.urls import *
import polls.views

urlpatterns = [

    url(r'^$', polls.views.upload, name = 'upload'),
    url(r'service_list/', polls.views.service_list, name = 'service_list'),
    #url(r'file_detail/', polls.views.file_detail, name = 'file_detail'),
    url(r'file_detail/(.+)/', polls.views.file_detail, name = 'file_detail'),
    #url(r'^admin/', admin.site.urls),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default = 0)
	def __str__(self):
		return self.choice_text

class File(models.Model):
	service = models.ForeignKey(Question, on_delete = models.CASCADE)
	#filename = models.CharField(max_length = 30)
	content = models.CharField(max_length = 200)
	upload_File = models.FileField(upload_to = './upload')
	uploaddate = models.DateTimeField('date uploaded')

	def __str__(self):
		return self.upload_File

	class Meta:
		ordering = ['-uploaddate']

class Service(models.Model):
	servicename = models.CharField(max_length = 30)
	uploaddate = models.DateTimeField('date upload')

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, render_to_response
from django import forms
from django.http import HttpResponse
from polls.models import *
from django.utils import timezone

class FileForm(forms.Form):
	servicename = forms.CharField()
	content = forms.CharField()
	upload_File = forms.FileField()

def upload(request):
	if request.method == "POST":
		ff = FileForm(request.POST, request.FILES)
		if ff.is_valid():
			#获取表单信息
			servicename = ff.cleaned_data['servicename']
			content = ff.cleaned_data['content']
			upload_File = ff.cleaned_data['upload_File']
			#写入数据库
			s = Service()
			s.servicename = servicename
			s.service_uploaddate = timezone.now()
			s.save()
			f = File()
			f.service = s
			f.content = content
			f.upload_File = upload_File
			f.uploaddate = timezone.now()
			f.save()
			
			services = Service.objects.order_by('servicename')   #distinct表示重复出现只选取一次
			return render_to_response('service_list.html',{'services':services})
			#return HttpResponse('upload successfully!')
	else:
		ff = FileForm()
	return render(request, 'upload.html',{'ff':ff})

def service_list(request):
	services = Serv.objects.order_by('servicename')     #distinct表示重复出现只选取一次
	return render_to_response('service_list.html',{'services':services})

#def file_detail(request):
#	files = File.objects.order_by('-uploaddate').all()     #负号表示降序
#	return render_to_response('file_detail.html',{'files':files})

def file_detail(request, fn):
	files = File.objects.order_by('-uploaddate')
	return render_to_response('file_detail.html', {'files':files})


# Create your views here.

polls/templates/file_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>File List</title>
	<style type="text/css">
	.text{text-align: center}
	.bottom{border-bottom-style: dashed; border-bottom-width: 1px}
	th{background-color:#c3dde0; width:180px;}
	td{width:180px;}
	</style>
</head>
<body>
	<h2 class = "text">{{files.first}}的配置列表</h2>
	<center>
	<table border="1"  cellspacing="0" cellpadding="0">
		<tr class = "text">
			<th>配置文件</th>
			<th>上传时间</th>
			<th>配置更新描述</th>
		</tr>
		{% for file in files %}
		<tr>
			<td>{{file.upload_File}}</td>
			<td>{{file.uploaddate|date:"Y-m-d H:i:s"}}</td>
			<td>{{file.content}}</td>
		</tr>
		{% endfor%}
	</table>
	</center>
</body>
</html>

polls/templates/service_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>File List</title>
	<style type="text/css">
	.text{text-align: center}
	.bottom{border-bottom-style: dashed; border-bottom-width: 1px}
	th{background-color:#c3dde0; width:180px;}
	td{width:180px;}
	</style>
</head>
<body>
	<center>
	<h2>服务列表</h2>
	<table cellspacing="0" cellpadding="0">
		<tr class = "text">
			<th>服务名称</th>
			<th>最后更新时间</th>
			<th>服务描述</th>
		</tr>
		{% for servcice in services %}
		<tr class = "text">
			<td><a href = "{% url 'upload:file_detail' service.servicename %}">{{service.servicename}}</a></td>
			<td>{{service.uploaddate|date:"Y-m-d H:i:s"}}</td>
		</tr>
		{% endfor%}
	</table>
	</center>
</body>
</html>

polls/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset = "UTF-8">
	<title>上传数据</title>
</head>
<body>
	<form method = "post" enctype = "multipart/form-data">
		{% csrf_token %} 
		{{ff.as_p}}
		<input type = "submit" value = "上传">
		<input type = "reset" value = "重置">
	</form>
</body>
</html>